name: Pylint
on: [push]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install pylint 
          pip install cython
          pip install -r requirements.txt
          pylint **/ogm
